### ISSUE TITLE
Windows 10 Taskbar shows as separate app

### ISSUE THREAD

**Issue by elbyte** [notion-enhancer/notion-repackaged#13]
Hiya,

Love the project, and the extra tweaks in this one compared to the base version are A++ awesome.
I'll be going back to the non-pre-enhanced version though for now. 

My main issue (which I know sounds trivial, but it bugs me a LOT) is that if I pin Notion Enhanced to the taskbar in windows 10, the application shows up as a separate item.  Doesn't happen with the non-repackaged version.

Keep up the good work.

**Comment by dragonwocky** [comment]
can you please show a screenshot? i haven't seen this before.
did you uninstall normal notion before installing the enhanced version?

**Comment by matfantinel** [comment]
I was having the same problem on Linux (elementary OS 6.0, based on Ubuntu 20.04), but with the "regular" repackaged version, not the enhanced one.

It was caused because the window class of the opened app was "notion-app", while the .desktop file declared it as "Notion". I fixed the following line on the .desktop file and it worked fine:

`StartupWMClass=notion-app`

I believe the cause of this issue on Windows might be similar, however I don't know if there's an equivalent fix there.

**Comment by starryyskies** [comment]
> I was having the same problem on Linux (elementary OS 6.0, based on Ubuntu 20.04), but with the "regular" repackaged version, not the enhanced one.
> 
> It was caused because the window class of the opened app was "notion-app", while the .desktop file declared it as "Notion". I fixed the following line on the .desktop file and it worked fine:
> 
> `StartupWMClass=notion-app`
> 
> I believe the cause of this issue on Windows might be similar, however I don't know if there's an equivalent fix there.

Could you do a screenshot or something to show where the .desktop file is? I'm a little new to this whole thing, so I'm having trouble finding it...

**Comment by Veriox** [comment]
Yep this is very annoying,

I wonder if there is a fix for this

**Comment by matfantinel** [comment]
@starryyskies the .desktop file is in this folder: `~/.local/share/applications` (you can paste it on the file manager bar to go directly to it)

Inside it you'll see the "StartupWMClass" line that you need to change to be like the one I sent on the previous comment.

**Comment by jamezrin** [comment]
I tried the app on Windows and I didn't have this problem. Make sure you clean every trace of the original Notion (no shortcuts, maybe check registry, etc...)
Maybe a screenshot of the task manager and desktop could help to debug this issue, maybe even a video recording of the desktop.


As for Linux users, where they had a bad .desktop file, this should be fixed in 2.0.16-2 (releasing now).

**Comment by dragonwocky** [comment]
confirmation from discord that this is still an issue
![image](https://user-images.githubusercontent.com/16874139/132988235-bd7da1a9-087e-4565-bfb4-04d5608d792e.png)

**Comment by jamezrin** [comment]
I just did a clean install of Windows 10 on a VM so I could try reproduce it, but it just works for me. The icon is good, I can pin the app and restart it without it being detected as a different app, etc. 

Admittedly, I only installed Notion Enhanced, maybe having the official Notion app (or some of its remnants) causes this issue.

**Comment by selimsandal** [comment]
![image](https://user-images.githubusercontent.com/49725809/134783993-76eb07e9-a81e-4c6d-b4ad-6a9af8c50d40.png)
still happens on latest update (2.0.16 r5)
Hope you can fix it

**Comment by dragonwocky** [comment]
@jamezrin I think there is a bug with the taskbar icon being misconfigured - when I open Notion enhanced, pin it, then close it and try reopen from the taskbar pin it opens the normal/unenhanced Notion app. I'm not sure if that's an electron-builder fix or something you want me to look into making a patch for some part of the app?

**Comment by jamezrin** [comment]
> @jamezrin I think there is a bug with the taskbar icon being misconfigured - when I open Notion enhanced, pin it, then close it and try reopen from the taskbar pin it opens the normal/unenhanced Notion app. Plus, it shows the Notion icon instead of the enhancer icon. I'm not sure if that's an electron-builder fix or something you want me to look into making a patch for some part of the app?

I can't reproduce the issue, I get a different behavior, see this quick repro video: https://youtu.be/ulaBxIeHg5I

**Comment by jacobhuesman** [comment]
I was able to resolve the problem by going into `%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Tombstones` and deleting the Notion shortcut. I'd had a previous install of the official Notion app. It looks like if you have an app pinned to your taskbar and uninstall it, Microsoft moves the shortcut to the `Tombstones` folder, which is then reused when you install Notion-Enhanced.

**Comment by Alfonso-Mij** [comment]
The solution for me was as simple as pinning the app (by searching it in the menu) to my taskbar and opening it. 

I don't know how it works, but as I had several issues with notion-enhancer I had to install and uninstall notion severl times. As I eventualy gave up (for the time), I found myself with se same problem. I checked the code and I assume it has to do with what @jacobhuesman said.
